---

extends:
  - "plugin:shopify/es5"
  - "plugin:shopify/node"
  - "plugin:shopify/jquery"
env:
  browser: true
  node: true
  jquery: true
globals:
  theme: true
  Shopify: false
  slate: true
  QRCode: false
rules:
  no-lonely-if: 0
  comma-dangle: 0
  spaced-comment: 0
  no-process-env: 0
  indent: ["error", 2, {"SwitchCase": 1}]
