#!/usr/bin/env node

const fs = require('fs');
const archiver = require('archiver');

module.exports = (
  buildZip('slate-src', ['src'], ['config-sample.yml'])
);

function buildZip(name, directories = [], files = []) {
  const output = fs.createWriteStream(`upload/${name}.zip`);
  const archive = archiver('zip');

  output.on('close', () => {
    console.log(`${name}.zip: ${archive.pointer()} total bytes`);
  });

  archive.on('error', (err) => {
    throw err;
  });

  archive.pipe(output);

  directories.forEach((directory) => {
    archive.directory(directory);
  });

  files.forEach((file) => {
    archive.file(file);
  });

  archive.finalize();
}
